{
  "before_install": [
    "gem install bundler",
    "sudo apt-get -y install unzip",
    "",
    "cd $TRAVIS_BUILD_DIR/public",
    "curl -o ~/wdn-compressed https://wdn.unl.edu/downloads/wdn.zip",
    "unzip -o ~/wdn-compressed -d wdn"
  ],
  "branches": {
    "only": [
      "travis-ci"
    ]
  },
  "language": "ruby",
  "rvm": [
    "2.7.0"
  ],
  "script": "cd $TRAVIS_BUILD_DIR/;bundle install rspec;rspec -I . unit_tests_spec.rb"
}