{
  "before_install": [
    "gem install bundler",
    "bundle install",
    "sudo apt-get -y install unzip",
    "sudo apt-get -y install ruby-rspec-core",
    "touch config/server.json",
    "sh config_setup.sh -u $DB_USER -p $DB_PASS -c $CAPTCHA_SITE_KEY -s $CAPTCHA_SECRET_KEY",
    "cd $TRAVIS_BUILD_DIR/public",
    "curl -o ./wdn-compressed https://wdn.unl.edu/downloads/wdn.zip",
    "unzip -o ./wdn-compressed -d wdn",
    "mv ./wdn/wdn/templates_5.3/ ./wdn/",
    "rm -rf ./wdn/wdn",
    "nvm install 16"
  ],
  "addons": {
    "sonarcloud": {
      "organization": "cseseniordesign",
      "token": "$SONAR_TOKEN"
    }
  },
  "branches": {
    "only": [
      "travis-ci"
    ]
  },
  "language": "ruby",
  "rvm": "2.7.0",
  "script": [
    "cd $TRAVIS_BUILD_DIR/",
    "rspec -I . unit_tests_spec.rb",
    "sonar-scanner"
  ]
}