{
  "before_install": [
    "gem install bundler",
    "gem install rspec-core",
    "bundle install",
    "sudo apt-get -y install unzip",
    "sudo apt-get -y install ruby-rspec-core",
    "touch config/config.json",
    "sh config_setup.sh -u DB_USER -p DB_PASS",
    "cd $TRAVIS_BUILD_DIR/public",
    "curl -o ~/wdn-compressed https://wdn.unl.edu/downloads/wdn.zip",
    "unzip -o ~/wdn-compressed -d wdn"
  ],
  "branches": {
    "only": [
      "travis-ci"
    ]
  },
  "language": "ruby",
  "rvm": [
    "2.7.0"
  ],
  "script": "cd $TRAVIS_BUILD_DIR/;rspec -I . unit_tests_spec.rb"
}